### ISSUE TITLE
[Question] Workflow DI

### ISSUE THREAD

**Issue by Zylius** [temporalio/sdk-php#111]
I've a question regarding workflows. I know I'm asking a lot of questions, when I'll have some free time I'll try to propose some PRs for them!

Now the question is: how do I inject something into a Workflow? I understand this could be a definite nono for temporal paradigm? Is it?

If not,  then, for example, currently we have our SAGA  (workflow) configs for each SAGA step (activity) in YAML files.

It's impossible to inject anything into the Workflow class. The constructor is always called without any arguments.

Should I use activity to get this stuff from container? Kinda sounds like it shouldn't be an "activity" of a specific workflow either.

Here's an example.

```php
#!/usr/bin/env php
<?php

use Temporal\Activity\ActivityOptions;
use Temporal\WorkerFactory;
use Temporal\Workflow\WorkflowInterface;

$myConfigs = ['greet_timeout' => 30];

#[WorkflowInterface]
class GreetingWorkflow
{
    private $greetingActivity;

    public function __construct(array $timeouts = [])
    {
        $this->greetingActivity = Workflow::newActivityStub(
            GreetingActivityInterface::class,
            
            // How to get this timeout setting ? 
            ActivityOptions::new()->withStartToCloseTimeout(
                CarbonInterval::seconds($timeouts['greet_timeout'])
            )
        );
    }

    public function greet(string $name): \Generator
    {
        return yield $this->greetingActivity->composeGreeting('Hello', $name);
    }
}

$factory = WorkerFactory::create();
$worker = $factory->newWorker();

// How do I register the workflow and inject the constructor params?
$worker->registerWorkflowTypes(GreetingWorkflow::class);

$factory->run();
```

**Comment by SerafimArts** [comment]
Hello! We deliberately avoided the possibility of injecting any variables inside the Workflow, since changing these values can change the behavior of this Workflow, which will break absolutely the entire code.

For example:
```php
#[WorkflowInterface]
class GreetingWorkflow
{
    public function __construct(private Some $service) {}
    
    public function greet(string $name): \Generator
    {
        if ($this->service->doSomething()) {
            yield $this->greetingActivity->composeGreeting('Hello', $name);
        }
        
        return yield $this->greetingActivity->composeGreeting('world', $name);
    }
}
```

In this case, the argument is a reference to an external service dependency that may have side effects that will break the workflow execution.

Moreover, when implementing the SDK, we focused on Java SDK, where there are no arguments for the workflow constructor.

However, the example with your code looks quite convincing. So we need to think about how to solve your problem.

**Comment by tsurdilo** [comment]
@Zylius 
as @SerafimArts mentioned, workflows must be deterministic, and you register the workflow type with the worker, not an instance.

You can achieve what you are looking for, I believe, with WorkflowClientInterface->startWithSignal (when you are starting your workflow execution, and not when you are registering your workflow with worker)

startWithSignal will start workflow execution (if no active ones is available) and send the signal on start. The data that you want to "inject" can be the signal data.

**Comment by Zylius** [comment]
Hey, thanks guys! I wasn't aware of `startWithSignal` and Signal functionality. I'll try it out! 

See what we're trying to do here, is generate temporal workflows (just like my past question about activities #110) from our legacy configuration. Now the example  you gave @SerafimArts, kinda got me a little worried. What I've been trying to avoid is generating "stub" php classes for workflows from our YAML files. But if that's what we have to do, I'll be willing to do it.

**Comment by wolfy-j** [comment]
FYI, with **local activities**, you will be able to "upload" the workflow config via calling the activity. It will be deterministic since it will freeze the workflow state in history.  (Local Activities are planned in the 1.1 version of this SDK).

This way workflow fully controls its config (i assume declarative DSL) and does not expose anything to the outside. This should solve your case without exposing anything.

@tsurdilo I believe the community can greatly benefit from a simple example of how to convert legacy DSL workflows into temporal workflows.

**Comment by wolfy-j** [comment]
Something like that:

```php
public function workflowMethod(string $type) 
{
     $yaml = yield $this->config->loadParsedConfig($type);

     // do something with yaml, the workflow is not detached from your config file and even if you changes it - it will remain deterministic

}
```

**Comment by Zylius** [comment]
Thank you very much! We've already done this and it works great. Kinda asked the question without fully understanding how temporal flow works. :bow:
