### ISSUE TITLE
[Question] Arrays not allowed as a return type?

### ISSUE THREAD

**Issue by Zylius** [temporalio/sdk-php#112]
Hello once again, I wanted to ask about [this](https://github.com/temporalio/sdk-php/blob/f53f1627f63fca73bd0e533831a8104bacd44309/src/DataConverter/Type.php#L104) line.

I was curious why is that. I'm sure there's a specific reason for it. I could still wrap it in a simple container object.
An example:

```php
#[ActivityInterface]
class WorkflowConfigActivity
{
    #[ActivityMethod]
    public function getTransactionConfigs(): array // Doesn't work
    {
        return ['my_config' => 'best_config'];
    }
}
```

**Comment by SerafimArts** [comment]
@Zylius hello! The reason is simple: Any iterator is generic, i.e. a composite type.

It is impossible to write in PHP:
```php
public function getTransactionConfigs(): array<string, string>
{
    // ...
}
```

In your case, there are two restrictions at the same time:
1) The absence of the concept of a hash map in JSON (There are only objects)
2) Inability to deduce an unambiguous type from return typehint.

In summary: Recommended to use DTOs to transfer composite objects between code.
Similar question: https://github.com/temporalio/sdk-php/issues/93

**Comment by Zylius** [comment]
Ahh gotya! Closing this ;) Thanks.
