### ISSUE TITLE
[Feature Request] Ability to use readonly properties in workflow and activity inputs.

### ISSUE THREAD

**Issue by kafkiansky** [temporalio/sdk-php#211]
Now each property is set individually after the object has been created. This does not work with `readonly` fields.

**Comment by shanginn** [comment]
I wanted to fix this, but was surprised, because readonly properties in DTO's are actually work.

I created demonstration [here](https://github.com/shanginn/temporal-php-worker/tree/feature-sdk-211-issue-demostration) for workflow argument and activity argument.

And pull request with unit test [here](https://github.com/temporalio/sdk-php/pull/232)
