### ISSUE TITLE
[SWOOLE] Integration With Other Async PHP Libraries

### ISSUE THREAD

**Issue by nickpoulos** [temporalio/sdk-php#294]
### Is your feature request related to a problem? Please describe.

We have a gRPC based application that uses Swoole under the hood. We would like to use this library to orchestrate some of our more complex workflows.  But based on the docs it seems in order to use all of the features of this SDK, the only choice we have as an async PHP library is RoadRunner.  

Are there plans or current documentation for using other similar async libraries like Swoole?  

### Describe the solution you'd like

I would like to use Swoole instead of RoadRunner while using this SDK.

**Comment by wolfy-j** [comment]
Porting to Swoole would mean that all of the SDK code has to be ported from Golang to C++, unfortunately, it's not just about porting async functions but much larger scope. 

We do not have such plans, as it, essentially, means maintaining two different versions of SDK.

Just a FYI for you, Swoole uses almost identical GRPC server declarations as RoadRunner. Mostly, because they used RoadRunner GRPC codebase as a foundation. :)
