### ISSUE TITLE
about connection refuse in tcp://127.0.0.1:6001

### ISSUE THREAD

**Issue by ru90** [temporalio/sdk-php#39]
when tried to execute workflow I got error that "enable to establish connection with tcp://127.0.0.1:6001"

**Comment by SerafimArts** [comment]
Lack of connection means that you are running the workflow outside the supervisor's environment: https://github.com/temporalio/roadrunner-temporal

**Comment by ru90** [comment]
how to run this alongside with temporal. I include this php temporal in my laravel project

**Comment by SerafimArts** [comment]
You should wait for the beta/release and then use the documentation: https://docs.temporal.io/docs/php-sdk-overview

Or compile the supervisor from the master branch: https://github.com/temporalio/roadrunner-temporal He will do the work of starting the workflow and/or activities using PHP Worker configuration.

**Comment by ru90** [comment]
> You should wait for the beta/release and then use the documentation: https://docs.temporal.io/docs/php-sdk-overview
> 
> Or compile the supervisor from the master branch: https://github.com/temporalio/roadrunner-temporal He will do the work of starting the workflow and/or activities using PHP Worker configuration.

I tried it but no luck. There has been built error also it( https://github.com/temporalio/roadrunner-temporal)seems to be is development phase

**Comment by wolfy-j** [comment]
Hi, we currently wait for go-sdk release since we did few internal changes. It should be available for test within a week or so.

**Comment by wolfy-j** [comment]
If you are familiar with Golang you can test it by yourself.

Go to https://github.com/temporalio/roadrunner-temporal 
Download go-sdk **master** and make sure that go.mod points to it https://github.com/temporalio/roadrunner-temporal/blob/master/go.mod#L22

Then you can follow the test instructions. If tests pass - you can build a file in the cmd directory and use .rr.yaml to run your workflows and activities.

Obviously, we will try to make it as easy as possible after finishing the release. With no need to build anything, we plan RR to include Temporal by default and be downloadable via composer.

However, you still need to make sure to install the GRPC extension to PHP in order to use the Temporal SDK client (which can work without host process).

**Comment by wolfy-j** [comment]
Hi, you can find working samples and instructions here: https://github.com/temporalio/samples-php
